language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
install:
- npm install --silent
script:
- npm run test
- npm run build
after_success:
- ".travis/push.sh"
deploy:
  provider: npm
  email: khoa.tan.nguyen.96@gmail.com
  api_key:
    secure: Jgm7+25RXr9J9PGjhGUIf+wpvgfMBEbvdLXdtG3MwIsPWfzaws2QLTwUDtshZL39S1lisien888du61wVaS8BxG2kfluI1VO8guQTirvplil3TAHk3+Te1W4I5UR7iTNn7XmPUd97RV7uhYtvoVda0/ZR9pjDbrhLYyIH9GQYY/vVnEo9GGkN4lEHSCnQnX467YR7SUBOLb5dzCkn+8XGbc5TmF7v88OtUevZ1kG2ZuZ9UQiKItVN9OEz56NSgahLOuf3nvzOLkH2cqJqnDprAnWuu+WOjyNxRb8W4Z6XJHqblXWOhdl+5LoCYOgnctOHaRi5YVmSatd1WaMHpI4B9RhkJm5fH3Iw/ddT/21hMtqPvFdk/6pvQ6mA6l+9LyxtynTLvuqwWwAVavqe/pXoR4xUkmG9CYpOnglYi7R/8UFRwAVHHQdFbMWMI7RkW8STxgYe23LKy2+1wV/o+1zD1CBtJlHa64aV9gh3NZW4AHUu+T2WO0A9PcJ9M3ZMS4YsAb0572ER9+HGx+KTKv3Mu+SzlHmuQkdjBMYw39luYLQRLqbkf4RwXTG5W5So56TP4V9eoQO3aVvyLpaj9UUQ3JLCa6JfsW/hveexcdLaE/rWdK2tH78byUDQ+ef1LyfCzrhxY8PgJhsN6WkxakucicM4Z0BDPIfyJjF66TUpE4=
  on:
    tags: true
    repo: khoanguyen96/Gallery
env:
  global:
    secure: nyBzrxlggkWZAKIKnx6Gq/UujS9dE/mYb6Rzz5t1T1Nu8XYe9gug0gMo6m/rdjz5d4yxtkrKUz7NpYpb9oaAkjQlmXdZ55M11VRSQ8iCq2YDu2zbllThHpkOsblzNyFpeySRfFqYC0XO8dtMwuTtZigiFi2ENVp30waWIZ0tN1oBfrPlyoSvOL6KoQvOedow+PRROLOIUlE+ODtjGoMXxBK6ebkBtaqO+tDCMzfZyd4guZszuhTICxY3aGrwxcS3DBy43ghV+d6ruvWTD1Y29+BJB5xz1jBf6h6nolEXIKsg2Oi0ppByiIE3aRWqaLzAlUq3BVvGmRCcMYA+X/8DYkjV2brvhjQqMX+PAwv27JCeJQHJXR5NB7kDf80npygGLA/YRVYjMIsCMu27GMqn2aNyT5XjFcjTB1V3dnrW0vf9YdR7jKdE/iHYETtLOiVLfzEvm5BK6DowGuH0vJ5BvGZNqRQ+jm3iAfk6aCxZOdNNdvyz8uzmLiwtKC5UotgiQAe2ATYuDJC7ARhJfiiF3W9QRoi93M/zJAAqZliQ9EsdgUMSRQfgkwcZZWdJJLPye3aGTl4FL/scvLv8Ug2RCi3kYGQdZ2AubIJkU6UMQBREci+i+N0QRMRm1VWdjAcipyOjPS7QlHLYJhSfhcQn3QZh8V0WXpk44OXWgJIt0ng=
